// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Aseguradora
    {
        public Aseguradora()
        {
            DetalleAseguradora = new HashSet<DetalleAseguradora>();
        }

        public int IdAseguradora { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<DetalleAseguradora> DetalleAseguradora { get; set; }
    }
}