// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class HistoriaClinica
    {
        public HistoriaClinica()
        {
            Diagnostico = new HashSet<Diagnostico>();
        }

        public int IdHistoriaClinica { get; set; }
        public int? IdPaciente { get; set; }
        public DateTime? FechaApertura { get; set; }
        public bool? Estado { get; set; }

        public virtual Paciente IdPacienteNavigation { get; set; }
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
    }
}