// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Paciente
    {
        public Paciente()
        {
            Cita = new HashSet<Cita>();
            DetalleAseguradora = new HashSet<DetalleAseguradora>();
            HistoriaClinica = new HashSet<HistoriaClinica>();
        }

        public int IdPaciente { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public int? Edad { get; set; }
        public string Sexo { get; set; }
        public string NroDocumento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public bool? Estado { get; set; }
        public string Imagen { get; set; }

        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<DetalleAseguradora> DetalleAseguradora { get; set; }
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
    }
}