// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Cita
    {
        public int IdCita { get; set; }
        public int IdMedico { get; set; }
        public int IdPaciente { get; set; }
        public DateTime? FechaReserva { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string Hora { get; set; }

        public virtual Medico IdMedicoNavigation { get; set; }
        public virtual Paciente IdPacienteNavigation { get; set; }
    }
}