// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class DetalleAseguradora
    {
        public int IdDetAseguradora { get; set; }
        public int? IdAseguradora { get; set; }
        public int? IdPaciente { get; set; }
        public string TipoSeguroSalud { get; set; }
        public string Estado { get; set; }

        public virtual Aseguradora IdAseguradoraNavigation { get; set; }
        public virtual Paciente IdPacienteNavigation { get; set; }
    }
}