// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Diagnostico
    {
        public int IdDiagnostico { get; set; }
        public int IdHistoriaClinica { get; set; }
        public DateTime? FechaEmision { get; set; }
        public string Observacion { get; set; }
        public bool? Estado { get; set; }

        public virtual HistoriaClinica IdHistoriaClinicaNavigation { get; set; }
    }
}