// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class DiaSemana
    {
        public DiaSemana()
        {
            HorarioAtencion = new HashSet<HorarioAtencion>();
        }

        public int IdDiaSemana { get; set; }
        public string NombreDiaSemana { get; set; }

        public virtual ICollection<HorarioAtencion> HorarioAtencion { get; set; }
    }
}