// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Especialidad
    {
        public Especialidad()
        {
            Medico = new HashSet<Medico>();
        }

        public int IdEspecialidad { get; set; }
        public string Descripcion { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<Medico> Medico { get; set; }
    }
}