// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class HorarioAtencion
    {
        public int IdHorarioAtencion { get; set; }
        public int IdMedico { get; set; }
        public int IdHoraInicio { get; set; }
        public DateTime? Fecha { get; set; }
        public DateTime? FechaFin { get; set; }
        public bool? Estado { get; set; }
        public int? IdDiaSemana { get; set; }

        public virtual DiaSemana IdDiaSemanaNavigation { get; set; }
        public virtual Hora IdHoraInicioNavigation { get; set; }
        public virtual Medico IdMedicoNavigation { get; set; }
    }
}