// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Hora
    {
        public Hora()
        {
            HorarioAtencion = new HashSet<HorarioAtencion>();
        }

        public int IdHora { get; set; }
        public string Hora1 { get; set; }

        public virtual ICollection<HorarioAtencion> HorarioAtencion { get; set; }
    }
}