// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CapaApresentacao.Models
{
    public partial class Medico
    {
        public Medico()
        {
            Cita = new HashSet<Cita>();
            HorarioAtencion = new HashSet<HorarioAtencion>();
        }

        public int IdMedico { get; set; }
        public int IdEmpleado { get; set; }
        public int IdEspecialidad { get; set; }
        public bool? Estado { get; set; }

        public virtual Empleado IdEmpleadoNavigation { get; set; }
        public virtual Especialidad IdEspecialidadNavigation { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<HorarioAtencion> HorarioAtencion { get; set; }
    }
}